- id: doi:10.3389/fcell.2020.00020
  image: https://www.frontiersin.org/files/Articles/515160/fcell-08-00020-HTML/image_m/fcell-08-00020-g003.jpg
  extra-links:
    - type: journal
      link: https://www.frontiersin.org/articles/10.3389/fcell.2020.00020/full
      text: Data analysis
  tags:
  - Tumor epigenetics
  - Data analysis
  - DNA methylation
  - Methylation array
  topics:
  - Tumor epigenetics

- id: doi:10.1093/nar/gkz830
  image: https://dingwb.github.io/images/dnmivd.png
  extra-links:
    - type: journal
      link: https://sciwheel.com/fulltext/doi/10.1093/nar/gkz830
      text: Database
    - type: source
      link: http://www.unimd.org/dnmivd/
      text: Website
  tags:
  - Database
  - DNA methylation
  - Methylation array
  - Tumor epigenetics
  topics:
  - Tumor epigenetics
  
- id: doi:10.1016/j.stemcr.2018.01.001
  image: https://www.cell.com/cms/attachment/0e308b9f-9515-45c4-89d7-e08e26ffb1dc/gr3.jpg
  extra-links:
    - type: journal
      link: https://sciwheel.com/fulltext/doi/10.1016/j.stemcr.2018.01.001
      text: Data analysis
  tags:
  - RNA-Seq
  - Data analysis
  topics:
  - Data analysis
  
- id: 10.1016/j.lfs.2020.118786
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0024320520315393-gr3.jpg
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S0024320520315393
      text: Data analysis
  tags:
  - Data analysis
  - Data visualization
  - RNA-Seq
  topics:
  - Data analysis
   
- id: doi:10.1080/15592294.2019.1568178
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/kepi20/2019/kepi20.v014.i01/15592294.2019.1568178/20190218/images/large/kepi_a_1568178_f0002_c.jpeg
  extra-links:
    - type: journal
      link: https://academic.oup.com/nar/article/49/D1/D1445/5997440
      text: Pancancer biomarkers
  tags:
  - DNA methylation
  - Methylation array
  - Tumor epigenetics
  - Machine learning
  topics:
  - Tumor epigenetics

- id: 10.1093/nar/gkaa1042
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/49/D1/10.1093_nar_gkaa1042/1/gkaa1042fig1.jpeg?Expires=1683681491&Signature=dUND34-3c5F2FW1R-GtstcGs~TFpCMOtGTX2e4L5bwCC8iKGhGy9n2-wk70d33fQSFu~wFr8X-rp9NoBWOqEtqM5CMb2aAXNJ9DU9x5QfxGjzK~fQdh4aekS7PAQyNWXcoDJNSGwjIH807JQPVsXhlbYpdFklKVB8Fe9LkBsfAtrUka0QpWqUGdv7nfKQFLQZFsCIx4pt3o8HmKaN3ETowJZiH7AQaIpAYPo~0T96wuiube6dfbroWkNj~d8NlKQvEpSw~b-ScfjKmqcbykyH7hcsegOCzR7-N251A5SKzAH~m9wzzo3kjKVMNlrskyL1qDK~6ShHpLcVSQLf1JIUQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  extra-links:
    - type: journal
      link: https://academic.oup.com/nar/article/49/D1/D1445/5997440
      text: Data analysis
  tags:
  - Database
  - DNA methylation
  - Data analysis
  topics:
  - Data analysis

- id: 10.1016/j.xgen.2022.100144
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666979X22000775-fx1.jpg
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S2666979X22000775
      text: Data analysis
  tags:
  - Data analysis
  - DNA methylation
  - Methylation array
  topics:
  - Data analysis

- id: doi:10.1093/bib/bbac617
  image: https://dingwb.github.io/images/sesame1.png
  extra-links:
    - type: journal
      link: https://www.researchgate.net/publication/366976018_Comparative_epigenome_analysis_using_Infinium_DNA_methylation_BeadChips#fullTextFileContent
      text: Software development
  tags:
  - DNA methylation
  - Methylation array
  - Software
  topics:
  - Software development

- id: doi:10.1002/imt2.89
  image: https://onlinelibrary.wiley.com/cms/asset/41728a1f-5566-4336-b6ec-64170426f8e0/imt289-fig-0002-m.jpg
  extra-links:
    - type: journal
      link: https://onlinelibrary.wiley.com/doi/full/10.1002/imt2.89
      text: Data visualization
  tags:
  - Data visualization
  topics:
  - Data visualization

- id: doi:10.1002/imt2.115
  image: https://onlinelibrary.wiley.com/cms/asset/da055c5b-a00f-4b9a-8e98-0dd0a6155326/imt2115-gra-0001-m.jpg
  extra-links:
    - type: journal
      link: https://onlinelibrary.wiley.com/doi/10.1002/imt2.115
      text: Data visualization
  tags:
  - Data visualization
  - Data analysis
  topics:
  - Data visualization
  - Software development